### ISSUE TITLE
Request to add autoBack API enhancement

### ISSUE THREAD

**Issue by Venger2005** [hakt0-r/homebridge-platform-linktap#5]
Is it possible to restore the previous program once the Instant Mode watering has finished using the 'autoBack' function in the API?  Thanks.

**Comment by hakt0-r** [comment]
changes committed. Please test and let me know if it works mate. 😃

**Comment by Venger2005** [comment]
Thanks for your quick response and reply. Have updated and tested and it works. Many thanks again. 

Is there any progress towards making this appear as a Sprinkler accessory type in Homekit rather than a switch?  I see something similar has been done with the Orbit B-Hyve (https://github.com/codyc1515/homebridge-orbit-bhyve), so wasn't sure if this was something you'd been working towards?

**Comment by Venger2005** [comment]
Hi. With your previous change, autoback was working for me. Recently the app has a major update and since then autoback is no longer working with this plug-in.  Not sure if there were changes made to the API alongside the app revamp which have caused this behaviour?

Any help is appreciated as having to manually check now to make sure watering is going to occur as per my 7-day schedule, which kind of defeats the purpose of my linktap homebridge automation.
